/* ApplicationsDockItem.c generated by valac 0.56.14, the Vala compiler
 * generated from ApplicationsDockItem.vala, do not modify */

/**/
/*  Copyright (C) 2017 Rico Tzschichholz*/
/**/
/*  This program is free software: you can redistribute it and/or modify*/
/*  it under the terms of the GNU General Public License as published by*/
/*  the Free Software Foundation, either version 3 of the License, or*/
/*  (at your option) any later version.*/
/**/
/*  This program is distributed in the hope that it will be useful,*/
/*  but WITHOUT ANY WARRANTY; without even the implied warranty of*/
/*  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the*/
/*  GNU General Public License for more details.*/
/**/
/*  You should have received a copy of the GNU General Public License*/
/*  along with this program.  If not, see <http://www.gnu.org/licenses/>.*/
/**/

#include <plank.h>
#include <glib-object.h>
#include <gmenu-tree.h>
#include <glib.h>
#include <gdk/gdk.h>
#include <gee.h>
#include <gtk/gtk.h>
#include <gio/gio.h>
#include <stdlib.h>
#include <string.h>
#include <glib/gi18n-lib.h>
#include <gio/gdesktopappinfo.h>

#if !defined(VALA_EXTERN)
#if defined(_MSC_VER)
#define VALA_EXTERN __declspec(dllexport) extern
#elif __GNUC__ >= 4
#define VALA_EXTERN __attribute__((visibility("default"))) extern
#else
#define VALA_EXTERN extern
#endif
#endif

#define DOCKY_TYPE_APPLICATIONS_DOCK_ITEM (docky_applications_dock_item_get_type ())
#define DOCKY_APPLICATIONS_DOCK_ITEM(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), DOCKY_TYPE_APPLICATIONS_DOCK_ITEM, DockyApplicationsDockItem))
#define DOCKY_APPLICATIONS_DOCK_ITEM_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), DOCKY_TYPE_APPLICATIONS_DOCK_ITEM, DockyApplicationsDockItemClass))
#define DOCKY_IS_APPLICATIONS_DOCK_ITEM(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), DOCKY_TYPE_APPLICATIONS_DOCK_ITEM))
#define DOCKY_IS_APPLICATIONS_DOCK_ITEM_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), DOCKY_TYPE_APPLICATIONS_DOCK_ITEM))
#define DOCKY_APPLICATIONS_DOCK_ITEM_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), DOCKY_TYPE_APPLICATIONS_DOCK_ITEM, DockyApplicationsDockItemClass))

typedef struct _DockyApplicationsDockItem DockyApplicationsDockItem;
typedef struct _DockyApplicationsDockItemClass DockyApplicationsDockItemClass;
typedef struct _DockyApplicationsDockItemPrivate DockyApplicationsDockItemPrivate;
enum  {
	DOCKY_APPLICATIONS_DOCK_ITEM_0_PROPERTY,
	DOCKY_APPLICATIONS_DOCK_ITEM_NUM_PROPERTIES
};
static GParamSpec* docky_applications_dock_item_properties[DOCKY_APPLICATIONS_DOCK_ITEM_NUM_PROPERTIES];
#define _g_object_unref0(var) ((var == NULL) ? NULL : (var = (g_object_unref (var), NULL)))
#define _g_error_free0(var) ((var == NULL) ? NULL : (var = (g_error_free (var), NULL)))
#define __vala_GMenuTreeDirectory_free0(var) ((var == NULL) ? NULL : (var = (_vala_GMenuTreeDirectory_free (var), NULL)))
#define __vala_GMenuTreeIter_free0(var) ((var == NULL) ? NULL : (var = (_vala_GMenuTreeIter_free (var), NULL)))
#define _g_free0(var) (var = (g_free (var), NULL))
typedef struct _Block1Data Block1Data;
#define __vala_GMenuTreeEntry_free0(var) ((var == NULL) ? NULL : (var = (_vala_GMenuTreeEntry_free (var), NULL)))

struct _DockyApplicationsDockItem {
	PlankDockletItem parent_instance;
	DockyApplicationsDockItemPrivate * priv;
};

struct _DockyApplicationsDockItemClass {
	PlankDockletItemClass parent_class;
};

struct _DockyApplicationsDockItemPrivate {
	GMenuTree* apps_menu;
	GMutex apps_menu_mutex;
	gboolean apps_loaded;
};

struct _Block1Data {
	int _ref_count_;
	DockyApplicationsDockItem* self;
	const gchar* desktop_path;
};

static gint DockyApplicationsDockItem_private_offset;
static gpointer docky_applications_dock_item_parent_class = NULL;

VALA_EXTERN GType docky_applications_dock_item_get_type (void) G_GNUC_CONST ;
G_DEFINE_AUTOPTR_CLEANUP_FUNC (DockyApplicationsDockItem, g_object_unref)
static void docky_applications_dock_item_update_menu (DockyApplicationsDockItem* self);
static void _docky_applications_dock_item_update_menu_gmenu_tree_changed (GMenuTree* _sender,
                                                                   gpointer self);
VALA_EXTERN DockyApplicationsDockItem* docky_applications_dock_item_new_with_dockitem_file (GFile* file);
VALA_EXTERN DockyApplicationsDockItem* docky_applications_dock_item_construct_with_dockitem_file (GType object_type,
                                                                                      GFile* file);
static void* __lambda4_ (DockyApplicationsDockItem* self,
                  GError** error);
static gpointer ___lambda4__plank_task_func (gpointer self,
                                      GError** error);
static PlankAnimationType docky_applications_dock_item_real_on_scrolled (PlankDockElement* base,
                                                                  GdkScrollDirection direction,
                                                                  GdkModifierType mod,
                                                                  guint32 event_time);
static PlankAnimationType docky_applications_dock_item_real_on_clicked (PlankDockElement* base,
                                                                 PlankPopupButton button,
                                                                 GdkModifierType mod,
                                                                 guint32 event_time);
static GeeArrayList* docky_applications_dock_item_real_get_menu_items (PlankDockElement* base);
static void _vala_GMenuTreeDirectory_free (GMenuTreeDirectory* self);
static GtkMenuItem* docky_applications_dock_item_get_submenu_item (DockyApplicationsDockItem* self,
                                                            GMenuTreeDirectory* category);
static void _vala_GMenuTreeIter_free (GMenuTreeIter* self);
static void docky_applications_dock_item_submenu_item_activate (DockyApplicationsDockItem* self,
                                                         GtkMenuItem* item);
static void _docky_applications_dock_item_submenu_item_activate_gtk_menu_item_activate (GtkMenuItem* _sender,
                                                                                 gpointer self);
static gulong* _ulong_dup (gulong* self);
static GMenuTreeDirectory* _vala_GMenuTreeDirectory_copy (GMenuTreeDirectory* self);
static void docky_applications_dock_item_add_menu_items (DockyApplicationsDockItem* self,
                                                  GtkMenu* menu,
                                                  GMenuTreeDirectory* category);
static Block1Data* block1_data_ref (Block1Data* _data1_);
static void block1_data_unref (void * _userdata_);
static void ____lambda5_ (Block1Data* _data1_);
static void _____lambda5__gtk_menu_item_activate (GtkMenuItem* _sender,
                                           gpointer self);
static void _vala_GMenuTreeEntry_free (GMenuTreeEntry* self);
VALA_EXTERN DockyApplicationsDockItem* docky_applications_dock_item_new (void);
VALA_EXTERN DockyApplicationsDockItem* docky_applications_dock_item_construct (GType object_type);
static GObject * docky_applications_dock_item_constructor (GType type,
                                                    guint n_construct_properties,
                                                    GObjectConstructParam * construct_properties);
static void docky_applications_dock_item_finalize (GObject * obj);
static GType docky_applications_dock_item_get_type_once (void);
static void _vala_clear_GMutex (GMutex * mutex);
static void _vala_clear_GRecMutex (GRecMutex * mutex);
static void _vala_clear_GRWLock (GRWLock * mutex);
static void _vala_clear_GCond (GCond * mutex);

static inline gpointer
docky_applications_dock_item_get_instance_private (DockyApplicationsDockItem* self)
{
	return G_STRUCT_MEMBER_P (self, DockyApplicationsDockItem_private_offset);
}

static void
_docky_applications_dock_item_update_menu_gmenu_tree_changed (GMenuTree* _sender,
                                                              gpointer self)
{
#line 49 "ApplicationsDockItem.vala"
	docky_applications_dock_item_update_menu ((DockyApplicationsDockItem*) self);
#line 156 "ApplicationsDockItem.c"
}

/**
 * {@inheritDoc}
 */
DockyApplicationsDockItem*
docky_applications_dock_item_construct_with_dockitem_file (GType object_type,
                                                           GFile* file)
{
	DockyApplicationsDockItem * self = NULL;
	PlankDockItemPreferences* _tmp0_;
	PlankDockItemPreferences* _tmp1_;
#line 31 "ApplicationsDockItem.vala"
	g_return_val_if_fail (file != NULL, NULL);
#line 33 "ApplicationsDockItem.vala"
	_tmp0_ = plank_dock_item_preferences_new_with_file (file);
#line 33 "ApplicationsDockItem.vala"
	_tmp1_ = _tmp0_;
#line 33 "ApplicationsDockItem.vala"
	self = (DockyApplicationsDockItem*) g_object_new (object_type, "Prefs", _tmp1_, NULL);
#line 33 "ApplicationsDockItem.vala"
	_g_object_unref0 (_tmp1_);
#line 31 "ApplicationsDockItem.vala"
	return self;
#line 181 "ApplicationsDockItem.c"
}

DockyApplicationsDockItem*
docky_applications_dock_item_new_with_dockitem_file (GFile* file)
{
#line 31 "ApplicationsDockItem.vala"
	return docky_applications_dock_item_construct_with_dockitem_file (DOCKY_TYPE_APPLICATIONS_DOCK_ITEM, file);
#line 189 "ApplicationsDockItem.c"
}

static void*
__lambda4_ (DockyApplicationsDockItem* self,
            GError** error)
{
	GError* _inner_error0_ = NULL;
	void* result;
#line 55 "ApplicationsDockItem.vala"
	g_mutex_lock (&self->priv->apps_menu_mutex);
#line 200 "ApplicationsDockItem.c"
	{
		GMenuTree* _tmp0_;
#line 57 "ApplicationsDockItem.vala"
		_tmp0_ = self->priv->apps_menu;
#line 57 "ApplicationsDockItem.vala"
		gmenu_tree_load_sync (_tmp0_, &_inner_error0_);
#line 57 "ApplicationsDockItem.vala"
		if (G_UNLIKELY (_inner_error0_ != NULL)) {
#line 209 "ApplicationsDockItem.c"
			goto __catch0_g_error;
		}
#line 58 "ApplicationsDockItem.vala"
		self->priv->apps_loaded = TRUE;
#line 214 "ApplicationsDockItem.c"
	}
	goto __finally0;
	__catch0_g_error:
	{
		GError* e = NULL;
		GError* _tmp1_;
		const gchar* _tmp2_;
#line 56 "ApplicationsDockItem.vala"
		e = _inner_error0_;
#line 56 "ApplicationsDockItem.vala"
		_inner_error0_ = NULL;
#line 60 "ApplicationsDockItem.vala"
		_tmp1_ = e;
#line 60 "ApplicationsDockItem.vala"
		_tmp2_ = _tmp1_->message;
#line 60 "ApplicationsDockItem.vala"
		g_warning ("ApplicationsDockItem.vala:60: Failed to load applications (%s)", _tmp2_);
#line 61 "ApplicationsDockItem.vala"
		self->priv->apps_loaded = FALSE;
#line 56 "ApplicationsDockItem.vala"
		_g_error_free0 (e);
#line 236 "ApplicationsDockItem.c"
	}
	__finally0:
#line 56 "ApplicationsDockItem.vala"
	if (G_UNLIKELY (_inner_error0_ != NULL)) {
#line 56 "ApplicationsDockItem.vala"
		g_propagate_error (error, _inner_error0_);
#line 56 "ApplicationsDockItem.vala"
		return NULL;
#line 245 "ApplicationsDockItem.c"
	}
#line 63 "ApplicationsDockItem.vala"
	g_mutex_unlock (&self->priv->apps_menu_mutex);
#line 64 "ApplicationsDockItem.vala"
	result = NULL;
#line 64 "ApplicationsDockItem.vala"
	return result;
#line 253 "ApplicationsDockItem.c"
}

static gpointer
___lambda4__plank_task_func (gpointer self,
                             GError** error)
{
	gpointer result;
	result = __lambda4_ ((DockyApplicationsDockItem*) self, error);
#line 54 "ApplicationsDockItem.vala"
	return result;
#line 264 "ApplicationsDockItem.c"
}

static void
docky_applications_dock_item_update_menu (DockyApplicationsDockItem* self)
{
	PlankWorker* _tmp0_;
#line 52 "ApplicationsDockItem.vala"
	g_return_if_fail (self != NULL);
#line 54 "ApplicationsDockItem.vala"
	_tmp0_ = plank_worker_get_default ();
#line 54 "ApplicationsDockItem.vala"
	plank_worker_add_task_with_result (_tmp0_, G_TYPE_POINTER, NULL, NULL, ___lambda4__plank_task_func, g_object_ref (self), g_object_unref, PLANK_TASK_PRIORITY_HIGH, NULL, NULL);
#line 277 "ApplicationsDockItem.c"
}

static PlankAnimationType
docky_applications_dock_item_real_on_scrolled (PlankDockElement* base,
                                               GdkScrollDirection direction,
                                               GdkModifierType mod,
                                               guint32 event_time)
{
	DockyApplicationsDockItem * self;
	PlankAnimationType result;
#line 68 "ApplicationsDockItem.vala"
	self = (DockyApplicationsDockItem*) base;
#line 70 "ApplicationsDockItem.vala"
	result = PLANK_ANIMATION_TYPE_NONE;
#line 70 "ApplicationsDockItem.vala"
	return result;
#line 294 "ApplicationsDockItem.c"
}

static PlankAnimationType
docky_applications_dock_item_real_on_clicked (PlankDockElement* base,
                                              PlankPopupButton button,
                                              GdkModifierType mod,
                                              guint32 event_time)
{
	DockyApplicationsDockItem * self;
	PlankAnimationType result;
#line 73 "ApplicationsDockItem.vala"
	self = (DockyApplicationsDockItem*) base;
#line 75 "ApplicationsDockItem.vala"
	result = PLANK_ANIMATION_TYPE_NONE;
#line 75 "ApplicationsDockItem.vala"
	return result;
#line 311 "ApplicationsDockItem.c"
}

static void
_vala_GMenuTreeDirectory_free (GMenuTreeDirectory* self)
{
#line 88 "ApplicationsDockItem.vala"
	g_boxed_free (gmenu_tree_directory_get_type (), self);
#line 319 "ApplicationsDockItem.c"
}

static void
_vala_GMenuTreeIter_free (GMenuTreeIter* self)
{
#line 96 "ApplicationsDockItem.vala"
	g_boxed_free (gmenu_tree_iter_get_type (), self);
#line 327 "ApplicationsDockItem.c"
}

static GeeArrayList*
docky_applications_dock_item_real_get_menu_items (PlankDockElement* base)
{
	DockyApplicationsDockItem * self;
	GeeArrayList* items = NULL;
	GeeArrayList* _tmp0_;
	GMenuTreeIter* iter = NULL;
	GMenuTree* _tmp4_;
	GMenuTreeDirectory* _tmp5_;
	GMenuTreeDirectory* _tmp6_;
	GMenuTreeIter* _tmp7_;
	GMenuTreeIter* _tmp8_;
	GMenuTreeItemType type = 0;
	GeeArrayList* result;
#line 78 "ApplicationsDockItem.vala"
	self = (DockyApplicationsDockItem*) base;
#line 80 "ApplicationsDockItem.vala"
	_tmp0_ = gee_array_list_new (gtk_menu_item_get_type (), (GBoxedCopyFunc) g_object_ref, (GDestroyNotify) g_object_unref, NULL, NULL, NULL);
#line 80 "ApplicationsDockItem.vala"
	items = _tmp0_;
#line 82 "ApplicationsDockItem.vala"
	if (!self->priv->apps_loaded) {
#line 352 "ApplicationsDockItem.c"
		GtkMenuItem* item = NULL;
		GtkMenuItem* _tmp1_;
		GeeArrayList* _tmp2_;
		GtkMenuItem* _tmp3_;
#line 83 "ApplicationsDockItem.vala"
		_tmp1_ = plank_dock_element_create_menu_item (_ ("No applications available"), NULL, FALSE);
#line 83 "ApplicationsDockItem.vala"
		item = _tmp1_;
#line 84 "ApplicationsDockItem.vala"
		_tmp2_ = items;
#line 84 "ApplicationsDockItem.vala"
		_tmp3_ = item;
#line 84 "ApplicationsDockItem.vala"
		gee_abstract_collection_add ((GeeAbstractCollection*) _tmp2_, _tmp3_);
#line 85 "ApplicationsDockItem.vala"
		result = items;
#line 85 "ApplicationsDockItem.vala"
		_g_object_unref0 (item);
#line 85 "ApplicationsDockItem.vala"
		return result;
#line 373 "ApplicationsDockItem.c"
	}
#line 88 "ApplicationsDockItem.vala"
	_tmp4_ = self->priv->apps_menu;
#line 88 "ApplicationsDockItem.vala"
	_tmp5_ = gmenu_tree_get_root_directory (_tmp4_);
#line 88 "ApplicationsDockItem.vala"
	_tmp6_ = _tmp5_;
#line 88 "ApplicationsDockItem.vala"
	_tmp7_ = gmenu_tree_directory_iter (_tmp6_);
#line 88 "ApplicationsDockItem.vala"
	_tmp8_ = _tmp7_;
#line 88 "ApplicationsDockItem.vala"
	__vala_GMenuTreeDirectory_free0 (_tmp6_);
#line 88 "ApplicationsDockItem.vala"
	iter = _tmp8_;
#line 90 "ApplicationsDockItem.vala"
	while (TRUE) {
#line 391 "ApplicationsDockItem.c"
		GMenuTreeIter* _tmp9_;
		GeeArrayList* _tmp10_;
		GMenuTreeIter* _tmp11_;
		GMenuTreeDirectory* _tmp12_;
		GMenuTreeDirectory* _tmp13_;
		GtkMenuItem* _tmp14_;
		GtkMenuItem* _tmp15_;
#line 90 "ApplicationsDockItem.vala"
		_tmp9_ = iter;
#line 90 "ApplicationsDockItem.vala"
		type = gmenu_tree_iter_next (_tmp9_);
#line 90 "ApplicationsDockItem.vala"
		if (!(type != GMENU_TREE_ITEM_INVALID)) {
#line 90 "ApplicationsDockItem.vala"
			break;
#line 407 "ApplicationsDockItem.c"
		}
#line 91 "ApplicationsDockItem.vala"
		if (type != GMENU_TREE_ITEM_DIRECTORY) {
#line 92 "ApplicationsDockItem.vala"
			continue;
#line 413 "ApplicationsDockItem.c"
		}
#line 93 "ApplicationsDockItem.vala"
		_tmp10_ = items;
#line 93 "ApplicationsDockItem.vala"
		_tmp11_ = iter;
#line 93 "ApplicationsDockItem.vala"
		_tmp12_ = gmenu_tree_iter_get_directory (_tmp11_);
#line 93 "ApplicationsDockItem.vala"
		_tmp13_ = _tmp12_;
#line 93 "ApplicationsDockItem.vala"
		_tmp14_ = docky_applications_dock_item_get_submenu_item (self, _tmp13_);
#line 93 "ApplicationsDockItem.vala"
		_tmp15_ = _tmp14_;
#line 93 "ApplicationsDockItem.vala"
		gee_abstract_collection_add ((GeeAbstractCollection*) _tmp10_, _tmp15_);
#line 93 "ApplicationsDockItem.vala"
		_g_object_unref0 (_tmp15_);
#line 93 "ApplicationsDockItem.vala"
		__vala_GMenuTreeDirectory_free0 (_tmp13_);
#line 433 "ApplicationsDockItem.c"
	}
#line 96 "ApplicationsDockItem.vala"
	result = items;
#line 96 "ApplicationsDockItem.vala"
	__vala_GMenuTreeIter_free0 (iter);
#line 96 "ApplicationsDockItem.vala"
	return result;
#line 441 "ApplicationsDockItem.c"
}

static void
_docky_applications_dock_item_submenu_item_activate_gtk_menu_item_activate (GtkMenuItem* _sender,
                                                                            gpointer self)
{
#line 107 "ApplicationsDockItem.vala"
	docky_applications_dock_item_submenu_item_activate ((DockyApplicationsDockItem*) self, _sender);
#line 450 "ApplicationsDockItem.c"
}

static gulong*
_ulong_dup (gulong* self)
{
	gulong* dup;
#line 107 "ApplicationsDockItem.vala"
	dup = g_new0 (gulong, 1);
#line 107 "ApplicationsDockItem.vala"
	memcpy (dup, self, sizeof (gulong));
#line 107 "ApplicationsDockItem.vala"
	return dup;
#line 463 "ApplicationsDockItem.c"
}

static gpointer
__ulong_dup0 (gpointer self)
{
#line 107 "ApplicationsDockItem.vala"
	return self ? _ulong_dup (self) : NULL;
#line 471 "ApplicationsDockItem.c"
}

static GMenuTreeDirectory*
_vala_GMenuTreeDirectory_copy (GMenuTreeDirectory* self)
{
#line 109 "ApplicationsDockItem.vala"
	return g_boxed_copy (gmenu_tree_directory_get_type (), self);
#line 479 "ApplicationsDockItem.c"
}

static gpointer
__vala_GMenuTreeDirectory_copy0 (gpointer self)
{
#line 109 "ApplicationsDockItem.vala"
	return self ? _vala_GMenuTreeDirectory_copy (self) : NULL;
#line 487 "ApplicationsDockItem.c"
}

static GtkMenuItem*
docky_applications_dock_item_get_submenu_item (DockyApplicationsDockItem* self,
                                               GMenuTreeDirectory* category)
{
	gchar* _tmp0_ = NULL;
	GIcon* _tmp1_;
	gchar* _tmp2_;
	GtkMenuItem* item = NULL;
	const gchar* _tmp4_;
	GtkMenuItem* _tmp5_;
	GtkMenu* submenu = NULL;
	GtkMenu* _tmp6_;
	gulong* item_activate_id = NULL;
	gulong _tmp7_;
	gulong _tmp8_;
	gulong* _tmp9_;
	gulong* _tmp10_;
	GMenuTreeDirectory* _tmp11_;
	GtkMenuItem* result;
#line 99 "ApplicationsDockItem.vala"
	g_return_val_if_fail (self != NULL, NULL);
#line 99 "ApplicationsDockItem.vala"
	g_return_val_if_fail (category != NULL, NULL);
#line 101 "ApplicationsDockItem.vala"
	_tmp1_ = gmenu_tree_directory_get_icon (category);
#line 101 "ApplicationsDockItem.vala"
	_tmp2_ = plank_drawing_service_get_icon_from_gicon (_tmp1_);
#line 101 "ApplicationsDockItem.vala"
	_tmp0_ = _tmp2_;
#line 101 "ApplicationsDockItem.vala"
	if (_tmp0_ == NULL) {
#line 521 "ApplicationsDockItem.c"
		gchar* _tmp3_;
#line 101 "ApplicationsDockItem.vala"
		_tmp3_ = g_strdup ("");
#line 101 "ApplicationsDockItem.vala"
		_g_free0 (_tmp0_);
#line 101 "ApplicationsDockItem.vala"
		_tmp0_ = _tmp3_;
#line 529 "ApplicationsDockItem.c"
	}
#line 101 "ApplicationsDockItem.vala"
	_tmp4_ = gmenu_tree_directory_get_name (category);
#line 101 "ApplicationsDockItem.vala"
	_tmp5_ = plank_dock_element_create_menu_item (_tmp4_, _tmp0_, TRUE);
#line 101 "ApplicationsDockItem.vala"
	item = _tmp5_;
#line 102 "ApplicationsDockItem.vala"
	_tmp6_ = (GtkMenu*) gtk_menu_new ();
#line 102 "ApplicationsDockItem.vala"
	g_object_ref_sink (_tmp6_);
#line 102 "ApplicationsDockItem.vala"
	submenu = _tmp6_;
#line 103 "ApplicationsDockItem.vala"
	gtk_menu_item_set_submenu (item, submenu);
#line 104 "ApplicationsDockItem.vala"
	gtk_widget_show ((GtkWidget*) submenu);
#line 105 "ApplicationsDockItem.vala"
	gtk_widget_show ((GtkWidget*) item);
#line 107 "ApplicationsDockItem.vala"
	_tmp7_ = g_signal_connect_object (item, "activate", (GCallback) _docky_applications_dock_item_submenu_item_activate_gtk_menu_item_activate, self, 0);
#line 107 "ApplicationsDockItem.vala"
	_tmp8_ = _tmp7_;
#line 107 "ApplicationsDockItem.vala"
	_tmp9_ = __ulong_dup0 (&_tmp8_);
#line 107 "ApplicationsDockItem.vala"
	item_activate_id = _tmp9_;
#line 108 "ApplicationsDockItem.vala"
	_tmp10_ = __ulong_dup0 (item_activate_id);
#line 108 "ApplicationsDockItem.vala"
	g_object_set_data_full ((GObject*) item, "plank-applications-item-activate-id", _tmp10_, g_free);
#line 109 "ApplicationsDockItem.vala"
	_tmp11_ = __vala_GMenuTreeDirectory_copy0 (category);
#line 109 "ApplicationsDockItem.vala"
	g_object_set_data_full ((GObject*) item, "plank-applications-category", _tmp11_, _vala_GMenuTreeDirectory_free);
#line 111 "ApplicationsDockItem.vala"
	result = item;
#line 111 "ApplicationsDockItem.vala"
	_g_free0 (item_activate_id);
#line 111 "ApplicationsDockItem.vala"
	_g_object_unref0 (submenu);
#line 111 "ApplicationsDockItem.vala"
	_g_free0 (_tmp0_);
#line 111 "ApplicationsDockItem.vala"
	return result;
#line 575 "ApplicationsDockItem.c"
}

static void
docky_applications_dock_item_submenu_item_activate (DockyApplicationsDockItem* self,
                                                    GtkMenuItem* item)
{
	gulong* item_activate_id = NULL;
	gpointer _tmp0_;
	GMenuTreeDirectory* category = NULL;
	gpointer _tmp1_;
	GtkMenu* _tmp2_;
	GtkMenu* _tmp3_;
#line 114 "ApplicationsDockItem.vala"
	g_return_if_fail (self != NULL);
#line 114 "ApplicationsDockItem.vala"
	g_return_if_fail (item != NULL);
#line 116 "ApplicationsDockItem.vala"
	_tmp0_ = g_object_steal_data ((GObject*) item, "plank-applications-item-activate-id");
#line 116 "ApplicationsDockItem.vala"
	item_activate_id = (gulong*) _tmp0_;
#line 117 "ApplicationsDockItem.vala"
	g_signal_handler_disconnect (item, *item_activate_id);
#line 119 "ApplicationsDockItem.vala"
	_tmp1_ = g_object_steal_data ((GObject*) item, "plank-applications-category");
#line 119 "ApplicationsDockItem.vala"
	category = (GMenuTreeDirectory*) _tmp1_;
#line 120 "ApplicationsDockItem.vala"
	_tmp2_ = gtk_menu_item_get_submenu (item);
#line 120 "ApplicationsDockItem.vala"
	_tmp3_ = _tmp2_;
#line 120 "ApplicationsDockItem.vala"
	docky_applications_dock_item_add_menu_items (self, _tmp3_, category);
#line 114 "ApplicationsDockItem.vala"
	__vala_GMenuTreeDirectory_free0 (category);
#line 114 "ApplicationsDockItem.vala"
	_g_free0 (item_activate_id);
#line 612 "ApplicationsDockItem.c"
}

static Block1Data*
block1_data_ref (Block1Data* _data1_)
{
#line 128 "ApplicationsDockItem.vala"
	g_atomic_int_inc (&_data1_->_ref_count_);
#line 128 "ApplicationsDockItem.vala"
	return _data1_;
#line 622 "ApplicationsDockItem.c"
}

static void
block1_data_unref (void * _userdata_)
{
	Block1Data* _data1_;
	_data1_ = (Block1Data*) _userdata_;
#line 128 "ApplicationsDockItem.vala"
	if (g_atomic_int_dec_and_test (&_data1_->_ref_count_)) {
#line 632 "ApplicationsDockItem.c"
		DockyApplicationsDockItem* self;
#line 128 "ApplicationsDockItem.vala"
		self = _data1_->self;
#line 128 "ApplicationsDockItem.vala"
		_g_object_unref0 (self);
#line 128 "ApplicationsDockItem.vala"
		g_slice_free (Block1Data, _data1_);
#line 640 "ApplicationsDockItem.c"
	}
}

static void
____lambda5_ (Block1Data* _data1_)
{
	DockyApplicationsDockItem* self;
	PlankSystem* _tmp0_;
	const gchar* _tmp1_;
	GFile* _tmp2_;
	GFile* _tmp3_;
#line 137 "ApplicationsDockItem.vala"
	self = _data1_->self;
#line 138 "ApplicationsDockItem.vala"
	_tmp0_ = plank_system_get_default ();
#line 138 "ApplicationsDockItem.vala"
	_tmp1_ = _data1_->desktop_path;
#line 138 "ApplicationsDockItem.vala"
	_tmp2_ = g_file_new_for_path (_tmp1_);
#line 138 "ApplicationsDockItem.vala"
	_tmp3_ = _tmp2_;
#line 138 "ApplicationsDockItem.vala"
	plank_system_launch (_tmp0_, _tmp3_);
#line 138 "ApplicationsDockItem.vala"
	_g_object_unref0 (_tmp3_);
#line 666 "ApplicationsDockItem.c"
}

static void
_____lambda5__gtk_menu_item_activate (GtkMenuItem* _sender,
                                      gpointer self)
{
#line 137 "ApplicationsDockItem.vala"
	____lambda5_ (self);
#line 675 "ApplicationsDockItem.c"
}

static void
_vala_GMenuTreeEntry_free (GMenuTreeEntry* self)
{
#line 142 "ApplicationsDockItem.vala"
	g_boxed_free (gmenu_tree_entry_get_type (), self);
#line 683 "ApplicationsDockItem.c"
}

static void
docky_applications_dock_item_add_menu_items (DockyApplicationsDockItem* self,
                                             GtkMenu* menu,
                                             GMenuTreeDirectory* category)
{
	GMenuTreeIter* iter = NULL;
	GMenuTreeIter* _tmp0_;
	GMenuTreeItemType type = 0;
#line 123 "ApplicationsDockItem.vala"
	g_return_if_fail (self != NULL);
#line 123 "ApplicationsDockItem.vala"
	g_return_if_fail (menu != NULL);
#line 123 "ApplicationsDockItem.vala"
	g_return_if_fail (category != NULL);
#line 125 "ApplicationsDockItem.vala"
	_tmp0_ = gmenu_tree_directory_iter (category);
#line 125 "ApplicationsDockItem.vala"
	iter = _tmp0_;
#line 127 "ApplicationsDockItem.vala"
	while (TRUE) {
#line 706 "ApplicationsDockItem.c"
		GMenuTreeIter* _tmp1_;
#line 127 "ApplicationsDockItem.vala"
		_tmp1_ = iter;
#line 127 "ApplicationsDockItem.vala"
		type = gmenu_tree_iter_next (_tmp1_);
#line 127 "ApplicationsDockItem.vala"
		if (!(type != GMENU_TREE_ITEM_INVALID)) {
#line 127 "ApplicationsDockItem.vala"
			break;
#line 716 "ApplicationsDockItem.c"
		}
#line 128 "ApplicationsDockItem.vala"
		switch (type) {
#line 128 "ApplicationsDockItem.vala"
			case GMENU_TREE_ITEM_DIRECTORY:
#line 722 "ApplicationsDockItem.c"
			{
				GMenuTreeIter* _tmp2_;
				GMenuTreeDirectory* _tmp3_;
				GMenuTreeDirectory* _tmp4_;
				GtkMenuItem* _tmp5_;
				GtkMenuItem* _tmp6_;
#line 130 "ApplicationsDockItem.vala"
				_tmp2_ = iter;
#line 130 "ApplicationsDockItem.vala"
				_tmp3_ = gmenu_tree_iter_get_directory (_tmp2_);
#line 130 "ApplicationsDockItem.vala"
				_tmp4_ = _tmp3_;
#line 130 "ApplicationsDockItem.vala"
				_tmp5_ = docky_applications_dock_item_get_submenu_item (self, _tmp4_);
#line 130 "ApplicationsDockItem.vala"
				_tmp6_ = _tmp5_;
#line 130 "ApplicationsDockItem.vala"
				gtk_container_add ((GtkContainer*) menu, (GtkWidget*) _tmp6_);
#line 130 "ApplicationsDockItem.vala"
				_g_object_unref0 (_tmp6_);
#line 130 "ApplicationsDockItem.vala"
				__vala_GMenuTreeDirectory_free0 (_tmp4_);
#line 131 "ApplicationsDockItem.vala"
				break;
#line 747 "ApplicationsDockItem.c"
			}
#line 128 "ApplicationsDockItem.vala"
			case GMENU_TREE_ITEM_ENTRY:
#line 751 "ApplicationsDockItem.c"
			{
				Block1Data* _data1_;
				GMenuTreeEntry* entry = NULL;
				GMenuTreeIter* _tmp7_;
				GMenuTreeEntry* _tmp8_;
				GDesktopAppInfo* info = NULL;
				GMenuTreeEntry* _tmp9_;
				GDesktopAppInfo* _tmp10_;
				GMenuTreeEntry* _tmp11_;
				const gchar* _tmp12_;
				gchar* _tmp13_ = NULL;
				GDesktopAppInfo* _tmp14_;
				GIcon* _tmp15_;
				gchar* _tmp16_;
				GtkMenuItem* item = NULL;
				GDesktopAppInfo* _tmp18_;
				const gchar* _tmp19_;
				GtkMenuItem* _tmp20_;
				GtkMenuItem* _tmp21_;
				GtkMenuItem* _tmp22_;
				GtkMenuItem* _tmp23_;
#line 128 "ApplicationsDockItem.vala"
				_data1_ = g_slice_new0 (Block1Data);
#line 128 "ApplicationsDockItem.vala"
				_data1_->_ref_count_ = 1;
#line 128 "ApplicationsDockItem.vala"
				_data1_->self = g_object_ref (self);
#line 133 "ApplicationsDockItem.vala"
				_tmp7_ = iter;
#line 133 "ApplicationsDockItem.vala"
				_tmp8_ = gmenu_tree_iter_get_entry (_tmp7_);
#line 133 "ApplicationsDockItem.vala"
				entry = _tmp8_;
#line 134 "ApplicationsDockItem.vala"
				_tmp9_ = entry;
#line 134 "ApplicationsDockItem.vala"
				_tmp10_ = gmenu_tree_entry_get_app_info (_tmp9_);
#line 134 "ApplicationsDockItem.vala"
				info = _tmp10_;
#line 135 "ApplicationsDockItem.vala"
				_tmp11_ = entry;
#line 135 "ApplicationsDockItem.vala"
				_tmp12_ = gmenu_tree_entry_get_desktop_file_path (_tmp11_);
#line 135 "ApplicationsDockItem.vala"
				_data1_->desktop_path = _tmp12_;
#line 136 "ApplicationsDockItem.vala"
				_tmp14_ = info;
#line 136 "ApplicationsDockItem.vala"
				_tmp15_ = g_app_info_get_icon ((GAppInfo*) _tmp14_);
#line 136 "ApplicationsDockItem.vala"
				_tmp16_ = plank_drawing_service_get_icon_from_gicon (_tmp15_);
#line 136 "ApplicationsDockItem.vala"
				_tmp13_ = _tmp16_;
#line 136 "ApplicationsDockItem.vala"
				if (_tmp13_ == NULL) {
#line 807 "ApplicationsDockItem.c"
					gchar* _tmp17_;
#line 136 "ApplicationsDockItem.vala"
					_tmp17_ = g_strdup ("");
#line 136 "ApplicationsDockItem.vala"
					_g_free0 (_tmp13_);
#line 136 "ApplicationsDockItem.vala"
					_tmp13_ = _tmp17_;
#line 815 "ApplicationsDockItem.c"
				}
#line 136 "ApplicationsDockItem.vala"
				_tmp18_ = info;
#line 136 "ApplicationsDockItem.vala"
				_tmp19_ = g_app_info_get_display_name ((GAppInfo*) _tmp18_);
#line 136 "ApplicationsDockItem.vala"
				_tmp20_ = plank_dock_element_create_menu_item (_tmp19_, _tmp13_, TRUE);
#line 136 "ApplicationsDockItem.vala"
				item = _tmp20_;
#line 137 "ApplicationsDockItem.vala"
				_tmp21_ = item;
#line 137 "ApplicationsDockItem.vala"
				g_signal_connect_data (_tmp21_, "activate", (GCallback) _____lambda5__gtk_menu_item_activate, block1_data_ref (_data1_), (GClosureNotify) block1_data_unref, 0);
#line 140 "ApplicationsDockItem.vala"
				_tmp22_ = item;
#line 140 "ApplicationsDockItem.vala"
				gtk_widget_show ((GtkWidget*) _tmp22_);
#line 141 "ApplicationsDockItem.vala"
				_tmp23_ = item;
#line 141 "ApplicationsDockItem.vala"
				gtk_container_add ((GtkContainer*) menu, (GtkWidget*) _tmp23_);
#line 142 "ApplicationsDockItem.vala"
				_g_object_unref0 (item);
#line 142 "ApplicationsDockItem.vala"
				_g_free0 (_tmp13_);
#line 142 "ApplicationsDockItem.vala"
				__vala_GMenuTreeEntry_free0 (entry);
#line 142 "ApplicationsDockItem.vala"
				block1_data_unref (_data1_);
#line 142 "ApplicationsDockItem.vala"
				_data1_ = NULL;
#line 142 "ApplicationsDockItem.vala"
				break;
#line 849 "ApplicationsDockItem.c"
			}
			default:
#line 128 "ApplicationsDockItem.vala"
			break;
#line 854 "ApplicationsDockItem.c"
		}
	}
#line 123 "ApplicationsDockItem.vala"
	__vala_GMenuTreeIter_free0 (iter);
#line 859 "ApplicationsDockItem.c"
}

DockyApplicationsDockItem*
docky_applications_dock_item_construct (GType object_type)
{
	DockyApplicationsDockItem * self = NULL;
#line 22 "ApplicationsDockItem.vala"
	self = (DockyApplicationsDockItem*) plank_docklet_item_construct (object_type);
#line 22 "ApplicationsDockItem.vala"
	return self;
#line 870 "ApplicationsDockItem.c"
}

DockyApplicationsDockItem*
docky_applications_dock_item_new (void)
{
#line 22 "ApplicationsDockItem.vala"
	return docky_applications_dock_item_construct (DOCKY_TYPE_APPLICATIONS_DOCK_ITEM);
#line 878 "ApplicationsDockItem.c"
}

static GObject *
docky_applications_dock_item_constructor (GType type,
                                          guint n_construct_properties,
                                          GObjectConstructParam * construct_properties)
{
	GObject * obj;
	GObjectClass * parent_class;
	DockyApplicationsDockItem * self;
	GMenuTree* _tmp0_;
	GMenuTree* _tmp1_;
#line 36 "ApplicationsDockItem.vala"
	parent_class = G_OBJECT_CLASS (docky_applications_dock_item_parent_class);
#line 36 "ApplicationsDockItem.vala"
	obj = parent_class->constructor (type, n_construct_properties, construct_properties);
#line 36 "ApplicationsDockItem.vala"
	self = G_TYPE_CHECK_INSTANCE_CAST (obj, DOCKY_TYPE_APPLICATIONS_DOCK_ITEM, DockyApplicationsDockItem);
#line 38 "ApplicationsDockItem.vala"
	plank_dock_item_set_Icon ((PlankDockItem*) self, "gnome-applications;;gnome-main-menu");
#line 39 "ApplicationsDockItem.vala"
	plank_dock_element_set_Text ((PlankDockElement*) self, _ ("Applications"));
#line 41 "ApplicationsDockItem.vala"
	_tmp0_ = gmenu_tree_new ("applications.menu", GMENU_TREE_FLAGS_SORT_DISPLAY_NAME);
#line 41 "ApplicationsDockItem.vala"
	_g_object_unref0 (self->priv->apps_menu);
#line 41 "ApplicationsDockItem.vala"
	self->priv->apps_menu = _tmp0_;
#line 42 "ApplicationsDockItem.vala"
	_tmp1_ = self->priv->apps_menu;
#line 42 "ApplicationsDockItem.vala"
	g_signal_connect_object (_tmp1_, "changed", (GCallback) _docky_applications_dock_item_update_menu_gmenu_tree_changed, self, 0);
#line 43 "ApplicationsDockItem.vala"
	docky_applications_dock_item_update_menu (self);
#line 36 "ApplicationsDockItem.vala"
	return obj;
#line 915 "ApplicationsDockItem.c"
}

static void
docky_applications_dock_item_class_init (DockyApplicationsDockItemClass * klass,
                                         gpointer klass_data)
{
#line 22 "ApplicationsDockItem.vala"
	docky_applications_dock_item_parent_class = g_type_class_peek_parent (klass);
#line 22 "ApplicationsDockItem.vala"
	g_type_class_adjust_private_offset (klass, &DockyApplicationsDockItem_private_offset);
#line 22 "ApplicationsDockItem.vala"
	((PlankDockElementClass *) klass)->on_scrolled = (PlankAnimationType (*) (PlankDockElement*, GdkScrollDirection, GdkModifierType, guint32)) docky_applications_dock_item_real_on_scrolled;
#line 22 "ApplicationsDockItem.vala"
	((PlankDockElementClass *) klass)->on_clicked = (PlankAnimationType (*) (PlankDockElement*, PlankPopupButton, GdkModifierType, guint32)) docky_applications_dock_item_real_on_clicked;
#line 22 "ApplicationsDockItem.vala"
	((PlankDockElementClass *) klass)->get_menu_items = (GeeArrayList* (*) (PlankDockElement*)) docky_applications_dock_item_real_get_menu_items;
#line 22 "ApplicationsDockItem.vala"
	G_OBJECT_CLASS (klass)->constructor = docky_applications_dock_item_constructor;
#line 22 "ApplicationsDockItem.vala"
	G_OBJECT_CLASS (klass)->finalize = docky_applications_dock_item_finalize;
#line 936 "ApplicationsDockItem.c"
}

static void
docky_applications_dock_item_instance_init (DockyApplicationsDockItem * self,
                                            gpointer klass)
{
#line 22 "ApplicationsDockItem.vala"
	self->priv = docky_applications_dock_item_get_instance_private (self);
#line 945 "ApplicationsDockItem.c"
}

static void
docky_applications_dock_item_finalize (GObject * obj)
{
	DockyApplicationsDockItem * self;
	GMenuTree* _tmp0_;
#line 22 "ApplicationsDockItem.vala"
	self = G_TYPE_CHECK_INSTANCE_CAST (obj, DOCKY_TYPE_APPLICATIONS_DOCK_ITEM, DockyApplicationsDockItem);
#line 48 "ApplicationsDockItem.vala"
	_tmp0_ = self->priv->apps_menu;
#line 48 "ApplicationsDockItem.vala"
	if (_tmp0_ != NULL) {
#line 959 "ApplicationsDockItem.c"
		GMenuTree* _tmp1_;
		guint _tmp2_;
#line 49 "ApplicationsDockItem.vala"
		_tmp1_ = self->priv->apps_menu;
#line 49 "ApplicationsDockItem.vala"
		g_signal_parse_name ("changed", gmenu_tree_get_type (), &_tmp2_, NULL, FALSE);
#line 49 "ApplicationsDockItem.vala"
		g_signal_handlers_disconnect_matched (_tmp1_, G_SIGNAL_MATCH_ID | G_SIGNAL_MATCH_FUNC | G_SIGNAL_MATCH_DATA, _tmp2_, 0, NULL, (GCallback) _docky_applications_dock_item_update_menu_gmenu_tree_changed, self);
#line 968 "ApplicationsDockItem.c"
	}
#line 24 "ApplicationsDockItem.vala"
	_g_object_unref0 (self->priv->apps_menu);
#line 25 "ApplicationsDockItem.vala"
	_vala_clear_GMutex (&self->priv->apps_menu_mutex);
#line 22 "ApplicationsDockItem.vala"
	G_OBJECT_CLASS (docky_applications_dock_item_parent_class)->finalize (obj);
#line 976 "ApplicationsDockItem.c"
}

static GType
docky_applications_dock_item_get_type_once (void)
{
	static const GTypeInfo g_define_type_info = { sizeof (DockyApplicationsDockItemClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) docky_applications_dock_item_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (DockyApplicationsDockItem), 0, (GInstanceInitFunc) docky_applications_dock_item_instance_init, NULL };
	GType docky_applications_dock_item_type_id;
	docky_applications_dock_item_type_id = g_type_register_static (PLANK_TYPE_DOCKLET_ITEM, "DockyApplicationsDockItem", &g_define_type_info, 0);
	DockyApplicationsDockItem_private_offset = g_type_add_instance_private (docky_applications_dock_item_type_id, sizeof (DockyApplicationsDockItemPrivate));
	return docky_applications_dock_item_type_id;
}

GType
docky_applications_dock_item_get_type (void)
{
	static volatile gsize docky_applications_dock_item_type_id__once = 0;
	if (g_once_init_enter (&docky_applications_dock_item_type_id__once)) {
		GType docky_applications_dock_item_type_id;
		docky_applications_dock_item_type_id = docky_applications_dock_item_get_type_once ();
		g_once_init_leave (&docky_applications_dock_item_type_id__once, docky_applications_dock_item_type_id);
	}
	return docky_applications_dock_item_type_id__once;
}

static void
_vala_clear_GMutex (GMutex * mutex)
{
	GMutex zero_mutex = { 0 };
	if (memcmp (mutex, &zero_mutex, sizeof (GMutex))) {
		g_mutex_clear (mutex);
		memset (mutex, 0, sizeof (GMutex));
	}
}

static void
_vala_clear_GRecMutex (GRecMutex * mutex)
{
	GRecMutex zero_mutex = { 0 };
	if (memcmp (mutex, &zero_mutex, sizeof (GRecMutex))) {
		g_rec_mutex_clear (mutex);
		memset (mutex, 0, sizeof (GRecMutex));
	}
}

static void
_vala_clear_GRWLock (GRWLock * mutex)
{
	GRWLock zero_mutex = { 0 };
	if (memcmp (mutex, &zero_mutex, sizeof (GRWLock))) {
		g_rw_lock_clear (mutex);
		memset (mutex, 0, sizeof (GRWLock));
	}
}

static void
_vala_clear_GCond (GCond * mutex)
{
	GCond zero_mutex = { 0 };
	if (memcmp (mutex, &zero_mutex, sizeof (GCond))) {
		g_cond_clear (mutex);
		memset (mutex, 0, sizeof (GCond));
	}
}
